apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name:  k8s-multi-com-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: ugurcoruh.com
  dnsNames:
    - k8s.ugurcoruh.com
    - www.k8s.ugurcoruh.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - k8s.ugurcoruh.com
        - www.k8s.ugurcoruh.com